export const cars = [
  {
    id: 1,
    name: "Aspark Owl",
    brand: "Aspark",
    image: "Aspark Owl",
    year: 2020,
    topSpeed: "400 km/h",
    price: 3200000,
    location: "United States",
    description:
      "The world's first all-electric hypercar from Japan, featuring a revolutionary design and unprecedented acceleration capabilities.",
  },
  {
    id: 2,
    name: "Bugatti Chiron",
    brand: "Bugatti",
    image: "Bugatti Chiron",
    year: 2016,
    topSpeed: "420 km/h",
    price: 3300000,
    location: "Canada",
    description:
      "A masterpiece of automotive engineering, representing the pinnacle of luxury and performance with its iconic W16 engine.",
  },
  {
    id: 3,
    name: "Ferrari F40",
    brand: "Ferrari",
    image: "Ferrari F40",
    year: 1987,
    topSpeed: "320 km/h",
    price: 1600000,
    location: "Spain",
    description:
      "Enzo Ferrari's final masterpiece, a raw and uncompromising supercar that defined an era of automotive excellence.",
  },
  {
    id: 4,
    name: "Maserati Alfieri",
    brand: "Maserati",
    image: "Maserati Alfieri",
    year: 2023,
    topSpeed: "300 km/h",
    price: 200000,
    location: "Mexico",
    description:
      "A modern interpretation of Maserati's racing heritage, combining Italian elegance with cutting-edge technology.",
  },
  {
    id: 5,
    name: "Mercedes-Benz 300 SL",
    brand: "Mercedes-Benz",
    image: "Mercedes-Benz 300 SL",
    year: 1954,
    topSpeed: "260 km/h",
    price: 1300000,
    location: "United States",
    description:
      "The legendary 'Gullwing' that revolutionized automotive design and became an icon of post-war luxury motoring.",
  },
  {
    id: 6,
    name: "SSC Tuatara",
    brand: "SSC",
    image: "SSC Tautara",
    year: 2020,
    topSpeed: "532 km/h",
    price: 1900000,
    location: "Canada",
    description:
      "America's answer to hypercar supremacy, holding the record for the world's fastest production car.",
  },
  {
    id: 7,
    name: "Koenigsegg Jesko",
    brand: "Koenigsegg",
    image: "Koenigsegg Jesko",
    year: 2021,
    topSpeed: "483 km/h",
    price: 2800000,
    location: "Spain",
    description:
      "A technological marvel from Sweden, featuring revolutionary aerodynamics and a mind-bending 1600 horsepower.",
  },
  {
    id: 8,
    name: "Pagani Huayra",
    brand: "Pagani",
    image: "Pagani Huayra",
    year: 2012,
    topSpeed: "370 km/h",
    price: 2500000,
    location: "Mexico",
    description:
      "A rolling piece of art, combining Italian craftsmanship with aerospace-grade materials and engineering.",
  },
  {
    id: 9,
    name: "Lamborghini Sian",
    brand: "Lamborghini",
    image: "Lamborghini Sian",
    year: 2019,
    topSpeed: "350 km/h",
    price: 3600000,
    location: "United States",
    description:
      "Lamborghini's first hybrid hypercar, featuring revolutionary supercapacitor technology and futuristic design.",
  },
  {
    id: 10,
    name: "McLaren Speedtail",
    brand: "McLaren",
    image: "McLaren Speedtail",
    year: 2019,
    topSpeed: "403 km/h",
    price: 2200000,
    location: "Canada",
    description:
      "A three-seat hypercar that combines extreme speed with luxury, inspired by the legendary F1 road car.",
  },
  {
    id: 11,
    name: "Aston Martin Valkyrie",
    brand: "Aston Martin",
    image: "Aston Martin Valkyrie",
    year: 2021,
    topSpeed: "400 km/h",
    price: 3200000,
    location: "Spain",
    description:
      "A road-legal Formula 1 car, developed in collaboration with Red Bull Racing and featuring revolutionary aerodynamics.",
  },
  {
    id: 12,
    name: "Rimac Nevera",
    brand: "Rimac",
    image: "Rimac Nevera",
    year: 2021,
    topSpeed: "412 km/h",
    price: 2400000,
    location: "Mexico",
    description:
      "The world's most powerful electric hypercar, showcasing the future of automotive performance.",
  },
  {
    id: 13,
    name: "Ferrari LaFerrari",
    brand: "Ferrari",
    image: "Ferrari LaFerrari",
    year: 2013,
    topSpeed: "350 km/h",
    price: 1400000,
    location: "United States",
    description:
      "Ferrari's first hybrid hypercar, combining F1 technology with road-going performance.",
  },
  {
    id: 14,
    name: "Porsche 918 Spyder",
    brand: "Porsche",
    image: "Porsche 918 Spyder",
    year: 2013,
    topSpeed: "345 km/h",
    price: 845000,
    location: "Canada",
    description:
      "A technological tour de force that redefined what's possible in a hybrid supercar.",
  },
  {
    id: 15,
    name: "Hennessey Venom F5",
    brand: "Hennessey",
    image: "Hennessey Venom F5",
    year: 2021,
    topSpeed: "500 km/h",
    price: 2100000,
    location: "Spain",
    description:
      "An American hypercar built to break records, featuring a twin-turbo V8 producing over 1800 horsepower.",
  },
];
